---
- name: Copy filebeat file
  ansible.builtin.template:
    src: "{{ mdd_telemetry }}/filebeat.yml.j2"
    dest: "{{ telemetry_base_dir }}/filebeat.yml"
    mode: 0600

- name: Restart ELK Stack containers
  command: docker compose restart
  args:
    chdir: "{{ telemetry_base_dir }}"

- name: Check container state
  docker_container_info:
    name: elastic
  loop:
    - es01
    - kibana
    - filebeat
  register: container_info
  failed_when: container_info.container.State is not defined
