collections:
  - name: https://github.com/ciscodevnet/ansible-cml.git
    type: git
  - source: /tmp/ansible-mdd
    type: dir
  - name: https://github.com/model-driven-devops/ansible-nso.git
    type: git
  - name: amazon.aws
    source: https://galaxy.ansible.com
