---
# defaults file for common
mdd_group_list: "{{ regions }}"
mdd_data_root: "{{ lookup('env', 'PWD') }}/mdd-data"
mdd_device_dir: "{{ mdd_data_root }}/{{ mdd_group_list | reverse | join('/') }}/{{ inventory_hostname }}"
create_dirs: no