---
# Node configs
telemetry_host_group: 'telemetry'
telemetry_node_label: 'telemetry'
telemetry_url: "{{ telemetry_rest_url }}/jsonrpc"
telemetry_telegraf_dir: telemetry-stack/conf/telegraf
telemetry_base_dir: telemetry-stack
telemetry_host_address: "{{ hostvars[telemetry_node_label].ansible_host }}"

# Host IP
host_address: "{{ telemetry_host_address }}"

# Telegraf port
telegraf_port: "{{ lookup('env', 'TELEGRAF_PORT') | default ('57000', true) }}"

# Elastic configs
kibana_password: "{{ lookup('env', 'KIBANA_PASSWORD') | default ('changeme', true) }}"
elastic_username: "{{ lookup('env', 'ELASTIC_USERNAME') | default ('elastic', true) }}"
elastic_password: "{{ lookup('env', 'ELASTIC_PASSWORD') | default ('changeme', true) }}"
stack_version: "{{ lookup('env', 'STACK_VERSION') | default ('8.7.1', true) }}"
cluster_name: "{{ lookup('env', 'CLUSTER_NAME') | default ('elastic', true) }}"
license: "{{ lookup('env', 'LICENSE') | default ('basic', true) }}"
es_port: "{{ lookup('env', 'ES_PORT') | default ('9200', true) }}"
kibana_port: "{{ lookup('env', 'KIBANA_PORT') | default ('5601', true) }}"
filebeat_port: "{{ lookup('env', 'FILEBEAT_PORT') | default ('2055', true) }}"
kb_mem_limit: "{{ lookup('env', 'KB_MEM_LIMIT') | default ('1073741824', true) }}"
ls_mem_limit: "{{ lookup('env', 'LS_MEM_LIMIT') | default ('1073741824', true) }}"
encryption_key: "{{ lookup('env', 'encryption_key') | default ('c34d38b3a14956121ff2170e5030b471551370178f43e5626eec58b04a30fae2', true) }}"

# InfluxDB configs
influxdb_token: "{{ lookup('env', 'INFLUXDB_TOKEN') | default ('veryverysecuretoken', true) }}"
influxdb_org: "{{ lookup('env', 'INFLUXDB_ORG') | default ('testorg', true) }}"
influxdb_bucket: "{{ lookup('env', 'INFLUXDB_BUCKET') | default ('testbucket', true) }}"
influxdb_username: "{{ lookup('env', 'INFLUXDB_USERNAME') | default ('admin', true) }}"
influxdb_password: "{{ lookup('env', 'INFLUXDB_PASSWORD') | default ('password123', true) }}"
influxdb_port_backup: "{{ lookup('env', 'INFLUXDB_PORT') | default ('8083', true) }}"
influxdb_port: "{{ lookup('env', 'INFLUXDB_PORT') | default ('8086', true) }}"
ds_type: "{{ lookup('env', 'DS_TYPE') | default ('influxdb', true) }}"

# Influx var for sending data to
# is_influx_db: "{{ lookup('env', 'IS_INFLUX_DB') | default (false) }}"
is_influx_db: false

# Grafana configs
grafana_datasource_name: "{{ lookup('env', 'GRAFANA_DATASOURCE_NAME') | default ('Grafana InfluxDB', true) }}"
grafana_username: "{{ lookup('env', 'GRAFANA_USERNAME') | default ('admin', true) }}"
grafana_password: "{{ lookup('env', 'GRAFANA_PASSWORD') | default ('admin', true) }}"
grafana_port: "{{ lookup('env', 'GRAFANA_PORT') | default ('3000', true) }}"
grafana_main_dashboard_uid: "daeb367a-86ff-4d3d-9bc0-38a05f6f501a"
grafana_stig_fail_uid: "b9664b3b-12db-4a42-8f2e-be45c8b3691d"
measurement_name: "{{ lookup('env', 'GRAFANA_MEASUREMENT_NAME') | default ('Gitlab pipeline diagnostics', true) }}"

# Node username
telemetry_username: "{{ lookup('env', 'TELEMETRY_USERNAME') | default ('ubuntu', true) }}"
telemetry_password: "{{ lookup('env', 'TELEMETRY_PASSWORD') | default ('admin', true) }}"
