- name: Create Device Directory
  ansible.builtin.file:
    path: "{{ mdd_device_dir }}"
    state: directory

- include_role:
    name: ciscops.mdd.nso
    tasks_from: get_config

- set_fact:
    nso_device_config: "{{ nso_device_config | ansible.utils.remove_keys(target=['config', 'mdd:openconfig']) }}"

- include_role:
    name: ciscops.mdd.nso
    tasks_from: get_native
  vars:
    data: "{{ nso_device_config }}"

- name: Write Native Data to Device Directory
  copy:
    content: "{{ nso_device_native_config }}"
    dest: "{{ mdd_device_dir }}/{{ inventory_hostname }}.cfg"
