- include_role:
    name: ciscops.mdd.nso
    tasks_from: get_config

- name: Create Device Directory
  ansible.builtin.file:
    path: "{{ mdd_device_dir }}"
    state: directory
  
- name: Write Data to Device Directory
  copy:
    content: "---\nmdd_data:\n  config:\n{{ nso_device_config['config'] | to_nice_yaml(indent=2,sort_keys=False) | indent(4, True) }}"
    dest: "{{ mdd_device_dir }}/config-{{ inventory_hostname }}.yml"