- include_role:
    name: ciscops.mdd.nso
    tasks_from: get_config

- name: Create Device Directory
  ansible.builtin.file:
    path: "{{ mdd_device_dir }}"
    state: directory

- name: Transform Native Config to OC
  set_fact:
    oc_data: "{{ nso_device_config['config'] | ciscops.mdd.nso_oc }}"

- name: Write OC Data to Device Directory
  copy:
    content: "---\nmdd_data:\n  mdd:openconfig:\n    {{ item.key }}:\n{{ item.value | to_nice_yaml(indent=2,sort_keys=False) | indent(6, True) }}"
    dest: "{{ mdd_device_dir }}/oc-{{ (item.key | ansible.builtin.split(':'))[1] }}.yml"
  with_dict: "{{ oc_data['mdd_data']['mdd:openconfig'] }}"
  
- name: Write Native Data to Device Directory
  copy:
    content: "---\nmdd_data:\n  config:\n{{ oc_data['mdd_data']['config'] | to_nice_yaml(indent=2,sort_keys=False) | indent(4, True) }}"
    dest: "{{ mdd_device_dir }}/config-{{ inventory_hostname }}.yml"