---
nso_host_group: 'nso'
nso_url: "{{ nso_rest_url }}/jsonrpc"
nso_package_src: "{{ lookup('env', 'PWD') }}/packages"
nso_installer_name: "nso-5.5.3.linux.x86_64.signed.bin"
nso_install_dir: /opt/ncs/current
nso_run_dir: /var/opt/ncs
nso_etc_dir: /etc/ncs
nso_tmp_dir: /tmp/nso
nso_upload_dir: /tmp/nso
nso_java_opts: "-Xmx2G -Xms1G"
# Default username/password for the NSO host
# admin_user: ubuntu
# admin_password: admin
# ansible_user: "{{ admin_user }}"
# ansible_password: "{{ admin_password }}"
nso_username: "{{ lookup('env', 'NSO_USERNAME') | default ('ubuntu', true) }}"
nso_password: "{{ lookup('env', 'NSO_PASSWORD') | default ('admin', true) }}"
# The auth groups to add.  Override in the inventory
nso_auth_groups:
  default:
    remote_name: "admin"
    remote_password: "admin"
nso_default_ned: cisco-ios-cli-6.77
nso_ned_dict:
  ios: "cisco-ios-cli-6.77"
nso_package_repos:
  - name: mdd
    repo: https://github.com/model-driven-devops/nso-oc-services.git
    service_list:
      - mdd
nso_global_settings:
  ssh-algorithms:
    public-key:
      - ssh-ed25519
      - ecdsa-sha2-nistp256
      - ecdsa-sha2-nistp384
      - ecdsa-sha2-nistp521
      - rsa-sha2-512
      - rsa-sha2-256
      - ssh-rsa
      - ssh-dss
    cipher:
      - aes128-gcm@openssh.com
      - AEAD_AES_128_GCM
      - chacha20-poly1305@openssh.com
      - aes256-gcm@openssh.com
      - AEAD_AES_256_GCM
      - aes128-ctr
      - aes192-ctr
      - aes256-ctr
      - aes128-cbc
      - 3des-cbc
