---
#
# Name: files_in_path
#
# Purpose: To find all files matching a list of patterns in a path derived
# from a list of elements passed in:
#
# Inputs:
#   - mdd_dir_items
#   - mdd_file_patterns
#   - mdd_root
#
# Returns:
#   - mdd_file_list
#
# Set the first level of search as the mdd_data_root 
#
- set_fact:
    search_dir_list: "{{ [ mdd_data_root ] }}"
#
# Create a hierarchical directory derived from the list of elements passed in.
#
- name: Create search directory list
  set_fact:
    search_dir_list: "{{ search_dir_list + [ [ search_dir_list | last | default ('') , item ] | join('/') ] }}"
  loop: "{{ mdd_dir_items }}"

- name: Create Device Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{ search_dir_list }}"
  when: create_dirs | bool

#
# Find MDD data file in the path to the device from generic to specific.
#
- name: Find MDD data files in the directory
  find:
    paths: "{{ search_dir_list }}"
    patterns: "{{ mdd_file_patterns }}"
  register: find_results

- set_fact:
    mdd_file_list: "{{ find_results.files | map(attribute='path') | list }}"