---
- name: Get CDP Data for Devices
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  vars:
    start_from: 2
    layout: kamada_kawai
    inventory_dir: inventory
    scale: 500
    use_cat9kv: False
    default_cml_device_template:
      switch:
        node_definition: iosvl2
        ram: 768
        tags:
          - switch
        type: switch
      router:
        node_definition: csr1000v
        ram: 3072
        tags:
          - router
        type: router
      # l3switch:
      #   node_definition: Cat9000v
      #   image_definition: Cat9k
      #   ram: 18432
      #   cpus: 4
      #   tags:
      #     - l3switch
      #   type: l3switch
      l3switch:
        node_definition: iosvl2
        ram: 768
        tags:
          - l3switch
        type: l3switch
      ext_conn:
        node_definition: external_connector
        ram: 0
        tags: []
    # Default interface mapping for CML
    default_cml_default_mappings:
      Loopback(\d+): Loopback\1
      Vlan(\d+): Vlan\1
  tasks:

    - name: Get CDP data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: exec_command
      vars:
        nso_exec_command: show cdp neighbors    

    - set_fact:
        cdp_data: "{{ {'hostname': inventory_hostname, 'tags': tags if tags is defined else {}, 'cdp': nso_command_output} }}"

    - name: Create device list with CDP data
      set_fact:
        devices: "{{ groups['network'] | map('extract', hostvars, 'cdp_data') | list }}"
      run_once: yes

    - set_fact:
        cml_device_template: "{{ default_cml_device_template }}"
      when: cml_device_template is not defined

    - set_fact:
        cml_default_mappings: "{{ default_cml_default_mappings }}"
      when: cml_default_mappings is not defined

    - name: Generate topology
      ciscops.mdd.cml_lab:
        devices: "{{ devices }}"
        start_from: "{{ start_from }}"
        device_template: "{{ cml_device_template }}"
        default_mappings: "{{ cml_default_mappings }}"
        use_cat9kv: "{{ use_cat9kv | bool }}"
      register: results
      run_once: yes

    - name: "Layout graph using the {{ layout }} layout"
      set_fact:
        topology: "{{ results.topology | ciscops.mdd.graph(layout=layout,scale=scale) }}"
      run_once: yes
      when: not layout == 'none'

    - name: Create topology file
      copy:
        content: "{{ topology | to_nice_yaml(indent=2,sort_keys=False) }}"
        dest: "{{ lookup('env', 'PWD') }}/files/cml_lab.yaml"
      run_once: yes
      no_log: yes

    - name: Create mapping file
      copy:
        content: "{{ {'all': {'hosts': results.mappings}} | to_nice_yaml(indent=2,sort_keys=False) }}"
        dest: "{{ lookup('env', 'PWD') }}/{{ inventory_dir }}/cml_intf_map.yml"
      run_once: yes
