---
- name: Get CDP Data for Devices
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  vars:
    start_from: 2
    layout: kamada_kawai
    scale: 500
    # Default device type mapping for CML
    default_cml_device_template:
      switch:
        node_definition: iosvl2
        tags:
          - switch
        type: switch
      router:
        node_definition: csr1000v
        tags:
          - router
        type: router
      l3switch:
        node_definition: iosvl2
        tags:
          - l3switch
        type: l3switch
      ext_conn:
        node_definition: external_connector
        tags: []
    # Default interface mapping for CML
    default_cml_default_mappings:
      Loopback(\d+): Loopback\1
      Port-channel(\d+): Port-channel\1
      Tunnel(\d+): Tunnel\1
      Vlan(\d+): Vlan\1
      vasileft(\d+): vasileft\1
      vasiright(\d+): vasiright\1
  tasks:

    - name: Get CDP data
      ansible.builtin.include_role:
        name: ciscops.mdd.nso
        tasks_from: exec_command
      vars:
        nso_exec_command: show cdp neighbors

    - name: Build CDP data table
      ansible.builtin.set_fact:
        cdp_data: "{{ {'hostname': inventory_hostname, 'tags': tags if tags is defined else {}, 'cdp': nso_command_output} }}"

    - name: Generate topology and mapping file
      run_once: True
      block:
        - name: Create device list with CDP data
          ansible.builtin.set_fact:
            devices: "{{ groups['network'] | map('extract', hostvars, 'cdp_data') | list }}"

        - name: Create device mapping table
          ansible.builtin.set_fact:
            cml_device_template: "{{ default_cml_device_template }}"
          when: cml_device_template is not defined

        - name: Create interface mapping table
          ansible.builtin.set_fact:
            cml_default_mappings: "{{ default_cml_default_mappings }}"
          when: cml_default_mappings is not defined

        - name: Get CML node definitions
          ansible.builtin.set_fact:
            cml_node_definitions: "{{ lookup('cisco.cml.cml_node_definition', None, cml_host=cml_host, cml_username=cml_username, cml_password=cml_password, allow_unsafe=True) }}"

        - name: Generate topology
          ciscops.mdd.cml_lab:
            devices: "{{ devices }}"
            start_from: "{{ start_from }}"
            device_template: "{{ cml_device_template }}"
            default_mappings: "{{ cml_default_mappings }}"
            node_definitions: "{{ cml_node_definitions }}"
          register: results

        - name: "Layout graph using the layout {{ layout }}"
          ansible.builtin.set_fact:
            topology: "{{ results.topology | ciscops.mdd.graph(layout=layout,scale=scale) }}"
          when: not layout == 'none'

        - name: Create topology file
          ansible.builtin.copy:
            content: "{{ topology | ansible.builtin.to_nice_yaml(indent=2, sort_keys=False) }}"
            dest: "{{ lookup('env', 'PWD') }}/files/cml_lab.yaml"
            mode: "0644"
          no_log: yes

        - name: Create mapping file
          ansible.builtin.copy:
            content: "{{ {'all': {'hosts': results.mappings}} | ansible.builtin.to_nice_yaml(indent=2, sort_keys=False) }}"
            dest: "{{ inventory_dir }}/cml_intf_map.yml"
            mode: "0644"
