- hosts: localhost
  gather_facts: no
  roles:
    - ciscops.mdd.netbox
  tasks:
    - cisco.cml.cml_lab_facts:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        # tags:
        #   - network
      register: cml_lab_results

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: netbox_inventory

    - name: Add new device
      include_role:
        name: ciscops.mdd.netbox
        tasks_from: add_device
      when: item.value.ansible_host_interface is defined and item.key not in netbox_host_list
      with_dict: "{{ cml_lab_results.cml_facts.nodes }}"
      vars:
        netbox_device_name: "{{ item.key }}"
        netbox_device_interface_name: "{{ item.value.ansible_host_interface }}"
        netbox_device_ipv4_address: "{{ item.value.ansible_host }}"
        netbox_device_type: unknown
        netbox_device_role: unknown
        # custom_fields:
        #   nso_host: "{{ nso_host }}"

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: netbox_mgmt
      when: item.value.ansible_host_interface is defined and item.value.ansible_host and item.key in netbox_host_list
      with_dict: "{{ cml_lab_results.cml_facts.nodes }}"
      vars:
        netbox_device_name: "{{ item.key }}"
        netbox_device_interface_name: "{{ item.value.ansible_host_interface }}"
        netbox_device_ipv4_address: "{{ item.value.ansible_host }}"