---
- name: elevate configs
  hosts: localhost
  gather_facts: false
  roles:
    - ciscops.mdd.data
  vars_prompt:
    - name: file_level_input
      prompt: "What file level would you like to elevate at?"
      private: false

    - name: test_run_bool
      prompt: "Would you like to see the results before committing? (yes/no)?"
      private: false

  tasks:
    - name: Convert is_test_run to boolean
      set_fact:
        is_test_run: "{{ test_run_bool | bool }}"
    - name: Convert file_level to boolean
      set_fact:
        file_level: "{{ file_level_input | int }}"

    - name: elevate
      elevate_configs:
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: "{{ is_test_run }}"
      register: elevate_result

    - debug:
        var: elevate_result.debug

    - pause:
        prompt: "Is this result okay? (yes/no)"
        echo: yes
      register: result
      when: is_test_run == true
    - set_fact:
        is_ok_continue: false
    - set_fact:
        is_ok_continue: "{{ result.user_input | bool }}"
      when: is_test_run == true

    - name: Delete created files
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ elevate_result.files_created }}"

    - name: elevate
      elevate_configs:
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: false
      register: result
      when: is_ok_continue == true
