---
- name: elevate configs
  hosts: localhost
  gather_facts: false
  roles:
    - ciscops.mdd.data

  vars:
    temp_dir: "{{ mdd_data_parent }}/temp_dir"
    file_level: "{{ level | default(-1) }}"
    is_test_run: "{{ test | default(false) }}"

  tasks:
    - name: elevate
      elevate_configs:
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: "{{ is_test_run }}"
        temp_dir: "{{ temp_dir }}"
      register: elevate_result

    - debug:
        var: elevate_result.debug

    - pause:
        prompt: "Is this result okay? (yes/no)"
        echo: yes
      register: result
      until: result.user_input.lower() in ['yes', 'no', 'y', 'n']
      retries: 5
      delay: 1
      when: is_test_run == true

    - set_fact:
        is_ok_continue: false
    - set_fact:
        is_ok_continue: true
      when: is_test_run == true and result.user_input.lower() in ['yes', 'y']

    - name: Delete temp directory if present
      file:
        path: "{{ temp_dir }}/"
        state: absent
      when: is_ok_continue == false

    - name: CP file
      elevate_configs:
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: false
        temp_dir: "{{ temp_dir }}"
      register: result
      when: is_ok_continue == true


