- name: Update Data in NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
    - ciscops.mdd.data
  vars:
    dry_run: true
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: check_sync

    - name: Get Device Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: get_config

    - name: Combine Device Data with OC Data
      set_fact:
        nso_device_config: "{{ nso_device_config | default({}) | ansible.builtin.combine( { 'mdd:openconfig': mdd_data['mdd:openconfig'] } ) }}"
      when: ('oc' in mdd_data_types)

    # - name: Combine Device Data with MDD Data
    #   set_fact:
    #     nso_device_config: "{{ nso_device_config | ansible.builtin.combine( { 'config': mdd_data['config'] }, recursive=true) }}"
    #   when: mdd_data['config'] is defined and mdd_data['mdd:openconfig'] is defined

    - name: Combine Device Data with MDD Data
      set_fact:
        nso_device_config: "{{ nso_device_config | ansible.builtin.combine( { 'config': mdd_data['config'] }) }}"
      when: ('config' in mdd_data_types) and not ('oc' in mdd_data_types)

    - name: Update MDD Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_data
      vars:
        mode: replace
        data: "{{ nso_device_config }}"
      when: mdd_data is defined

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: update_rollback_list
      when: rollback_id is defined and rollback_id and netbox_available | default(false)

- name: Run update_report
  hosts: network
  connection: local
  gather_facts: no
  vars:
    dry_run: true
  tasks:
    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_report
      run_once: true
      when: dry_run | bool
