- name: Merge Data in NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
    - ciscops.mdd.data
  vars:
    dry_run: true
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: check_sync

    - name: Translate/truncate interface names and truncate config
      set_fact:
        mdd_data: "{{ mdd_data | ciscops.mdd.config_xform(cml_intf_xlate | default(None), cml_truncate_list | default(None), cml_vlan_list | default(None)) }}"
      when: (cml_intf_xlate is defined and cml_intf_xlate) or (cml_truncate_list is defined and cml_truncate_list) or (cml_vlan_list is defined and cml_vlan_list)

    - name: Merge Config Data
      when: ('config' in mdd_data_types)
      block:
      - set_fact:
          mdd_data: "{{ mdd_data | ansible.utils.remove_keys(target=['mdd:openconfig']) }}"

      - name: Merge Data
        include_role:
          name: ciscops.mdd.nso
          tasks_from: update_data
        vars:
          mode: merge
        when: mdd_data is defined and 'config' in mdd_data

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: update_rollback_list
      when: rollback_id is defined and rollback_id and netbox_available | default(false)

- name: Run update_report
  hosts: network
  connection: local
  gather_facts: no
  vars:
    dry_run: true
  tasks:
    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_report
      run_once: true
      when: dry_run | bool
