- name: Update OC Data in NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
    - ciscops.mdd.data
  vars:
    dry_run: true
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: check_sync

    - name: Translate and truncate interface names
      set_fact:
        mdd_data: "{{ mdd_data | ciscops.mdd.intf_xform(cml_intf_xlate) }}"
      when: (cml_group in group_names) and (cml_intf_xlate is defined and cml_intf_xlate)

    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_data
      vars:
        mode: replace
        path: '/ncs:devices/device{{ "{" }}{{ inventory_hostname }}{{ "}" }}/mdd:openconfig'
        data: "{{ mdd_data['mdd:openconfig'] }}"
      when: mdd_data['mdd:openconfig'] is defined

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: update_rollback_list
      when: rollback_id is defined and rollback_id and netbox_available | default(false)

- name: Run update_report
  hosts: all
  connection: local
  gather_facts: no
  vars:
    dry_run: true
  tasks:
    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_report
      run_once: true
      when: dry_run | bool
