- name: Harvest Data from NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.data
    - ciscops.mdd.nso
  vars:
    create_dirs: yes
  tasks:

    - include_role:
        name: ciscops.mdd.common
        tasks_from: files_in_path
      vars:
        mdd_file_patterns: "{{ mdd_data_patterns }}"

    - name: Harvest Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_yaml_data
