- name: Harvest Data from NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.data
    - ciscops.mdd.nso
  tasks:

    - name: Harvest Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_yaml_data
