- name: Harvest Native Config from NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.data
    - ciscops.mdd.nso
  tasks:

    - name: Harvest Native Config
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_native_config
