- name: Merge Data in NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
    - ciscops.mdd.data
  vars:
    dry_run: true
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: check_sync

    - name: Merge MDD Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_data
      vars:
        mode: merge
      when: mdd_data is defined

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: update_rollback_list
      when: rollback_id is defined and rollback_id and netbox_available | default(false)

- name: Run update_report
  hosts: network
  connection: local
  gather_facts: no
  vars:
    dry_run: true
  tasks:
    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_report
      run_once: true
      when: dry_run | bool
