- name: Start NSO
  hosts: nso
  gather_facts: no
  become: "{{ sudo_required }}"
  vars:
    sudo_required: yes
  roles:
    - ciscops.mdd.nso
  tasks:
    - name: Install MDD packages
      include_role:
        name: ciscops.mdd.nso
        tasks_from: install_packages
      tags:
        - packages
