- hosts: network
  connection: local
  gather_facts: no
  ignore_errors: yes
  roles:
    - ciscops.mdd.data      # Loads the MDD Data
    - ciscops.mdd.validate  # Validates the OC Data

- name: Run update_report
  hosts: network
  connection: local
  gather_facts: no
  tasks:
    - name: Run Validation Report
      include_role:
        name: ciscops.mdd.validate
        tasks_from: validation_report
      run_once: true

    - name: Send validation report
      include_role:
        name: ciscops.mdd.telemetry
        tasks_from: send_telemetry
      run_once: true

    - fail:
        msg: "Failed Validation"
      when: validation_failures is defined and validation_failures
